### ISSUE TITLE
Can you please provide usage examples

### ISSUE THREAD

**Issue by sjt003** [SwiftsNamesake/please-focus#1]
This lib could do with some examples.

**Comment by SwiftsNamesake** [comment]
You're right. I wasn't expecting anyone else but myself to use it to be honest, and it's still under development.

**Comment by SwiftsNamesake** [comment]
I cobbled together a tutorial, Have a look and let me know what you think.

**Comment by sjt003** [comment]
looks great, but I could really use an example of updating nested fields. that is really the attraction of this lib. thanks.

**Comment by SwiftsNamesake** [comment]
Have a look at the very last example (nickname=>first)

I'll clean up the docs when I have time (maybe adding an index or an FAQ) but most info is in there. 

Probably should've been more explicit though.

There already is a lens library for Elm, so I'm not sure how much effort I should put into this, but there's a lot
of work to be done still which may require an overhaul of the docs.

**Comment by SwiftsNamesake** [comment]
Pinging @sjt003 for a response...

**Comment by sjt003** [comment]
these examples still dont work for me

**Comment by SwiftsNamesake** [comment]
What do you mean by that?

**Comment by sjt003** [comment]
![screenshot from 2017-03-10 09 41 20](https://cloud.githubusercontent.com/assets/2036561/23801450/d29eabca-0575-11e7-8985-86a43f69cf0d.png)

**Comment by sjt003** [comment]
I simply can't get the first setter example to work

**Comment by sjt003** [comment]
none of the examples work, in fact. maybe I'm dong something wrong...

**Comment by SwiftsNamesake** [comment]
The issue seems to be with operator precedence. You need parentheses around the operands to `.=`:
    santa & (nickname .= "Saint Nicholas")

If you give me a few minutes I'll try to fix the precedence issue. Apologies for the inconvenience.

**Comment by SwiftsNamesake** [comment]
It should work without parentheses now. I've tried it in the REPL. Good luck and apologies again.

**Comment by sjt003** [comment]
works thank you!
